- hosts: localhost
  tasks:
     - name: Create a github Repo
       github_repo:
        github_auth_key: "eac88a913ff42fb80d35379711c051625c0c3688"
        name: "install-create-module"
        description: "Ansible module for github"
        private: no
        has_issues: no
        has_wiki: no
        has_downloads: no
        state: present
       register: result